# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: docker compose build
    command: URL_PATTERN=$(gp url 5555 | sed 's@5555@%s@') docker compose up -d
  - command: brew tap sigstore/tap && brew install gitsign && brew install cosign

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Rekor
    description: Rekor
    port: 3000
    visibility: public
  - name: Fulcio
    description: Fulcio 
    port: 5555
    visibility: public
  - name: Dex
    description: Dex
    port: 5556
    visibility: public
  - name: CTLog
    description: CTLog
    port: 6962
    visibility: public
  - name: TUF
    description: TUF
    port: 8080
    visibility: public

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
