# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Rekor
    description: Rekor
    port: 3000
    visibility: public
  - name: Fulcio
    description: Fulcio 
    port: 5555
    visibility: public
  - name: Fulcio GRPC
    description: Fulcio GRPC
    port: 5554
    visibility: public
  - name: Dex
    description: Dex
    port: 5556
    visibility: public
  - name: CTLog
    description: CTLog
    port: 6962
    visibility: public

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
