services:
  #### fulcio ####
  fulcio:
    image: gcr.io/projectsigstore/fulcio:v1.4.0
    command:
      - serve
      - --port=5555
      - --grpc-port=5554
      - --ca=fileca
      - --fileca-key
      - /var/run/fulcio-secrets/int.key
      - --fileca-cert
      - /var/run/fulcio-secrets/int.crt
      - --fileca-key-passwd
      - $(cat /var/run/fulcio-ca-password)
      - --ct-log-url=http://ct_server:6962/trillian
    secrets:
      - fulcio-ca-password
    volumes:
      - ./fulcio-secrets:/var/run/fulcio-secrets/
      - ./fulcio-config:/etc/fulcio-config/
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    ports:
      - "5554:5554"
      - "5555:5555"
      - "2112:2112"
    depends_on:
      - dex
      - ct_server

  #### rekor ####
  redis:
    image: redis:6.2-alpine
    restart: always
    expose:
      - '6379:6379'
    command: redis-server

  rekor:
    image: gcr.io/projectsigstore/rekor-server:v1.3.0
    command:
      - serve
      - --rekor_server.address=0.0.0.0
      - --trillian_log_server.address=trillian-log-server
      - --trillian_log_server.port=8090
      - --redis_server.address=redis
      - --redis_server.port=6379
    depends_on:
      - trillian-log-server
      - redis
    restart: always
    ports:
      - "3000:3000"

  #### trillian ####
  mysql:
    image: gcr.io/trillian-opensource-ci/db_server:v1.5.2
    environment:
      - MYSQL_ROOT_PASSWORD=zaphod
      - MYSQL_DATABASE=trillian
      - MYSQL_USER=user
      - MYSQL_PASSWORD=zaphod
    restart: always # keep the MySQL server running

  trillian-log-server:
    image: gcr.io/projectsigstore/trillian_log_server:v1.3.0
    command: [
      "--storage_system=mysql",
      "--mysql_uri=user:zaphod@tcp(mysql:3306)/trillian",
      "--rpc_endpoint=0.0.0.0:8090",
      "--http_endpoint=0.0.0.0:8091",
      "--alsologtostderr",
    ]
    restart: always # retry while mysql is starting up
    expose:
      - "8090:8090" # grpc
      - "8091:8091" # http
    depends_on:
      - mysql

  trillian-log-signer:
    image: gcr.io/projectsigstore/trillian_log_signer:v1.3.0
    command: [
      "--storage_system=mysql",
      "--mysql_uri=user:zaphod@tcp(mysql:3306)/trillian",
      "--rpc_endpoint=0.0.0.0:8090",
      "--http_endpoint=0.0.0.0:8091",
      "--force_master",
      "--alsologtostderr",
    ]
    restart: always # retry while mysql is starting up
    expose:
      - "8090:8090" # grpc
      - "8091:8091" # http
    depends_on:
      - mysql

  #### ctlog ####
  ctfe_init:
    build:
      context: .
      dockerfile: Dockerfile.ctfe_init
    depends_on:
      - trillian-log-server
    volumes:
      - ./ctfeConfig:/etc/config/:rw

  ct_server:
    image: gcr.io/trillian-opensource-ci/ctfe
    volumes:
      - ./ctfeConfig:/etc/config/:ro
    command: [
        "--log_config" ,"/etc/config/ct_server.cfg",
        "--log_rpc_server", "trillian-log-server:8090",
        "--http_endpoint", "0.0.0.0:6962",
        "--alsologtostderr",
    ]
    restart: always # retry while ctfe_init is running
    depends_on:
      - trillian-log-server
      - trillian-log-signer
      - ctfe_init
    ports:
      - "6962:6962"

  #### dex ####

  dex:
    image: ghcr.io/dexidp/dex:v2.37.0
    restart: always
    command:
      - dex
      - serve
      - --web-http-addr
      - 0.0.0.0:5556
      - --telemetry-addr
      - 0.0.0.0:5558
      - /etc/dex/config.yaml
    ports:
      - "5556:5556"
    volumes:
      - ./dex:/etc/dex/

  #### tuf ####
  #### tsa ####

secrets:
  fulcio-ca-password:
    file: fulcio-secrets/password.txt

# volumes:
#   ctfeConfig: {}