# Set it to a valid URL
issuer: https://5556-chevrontang-sigstoretes-6n3nt8yrvpr.ws-eu104.gitpod.io

# See https://dexidp.io/docs/storage/ for more options
storage:
  type: memory

staticClients:
  - id: sigstore
    name: 'Sigstore'
    public: true

connectors:
  - type: mockCallback
    id: mock
    name: Example
