# Set it to a valid URL
issuer: http://my-issuer-url.com

# See https://dexidp.io/docs/storage/ for more options
storage:
  type: memory

# Enable at least one connector
# See https://dexidp.io/docs/connectors/ for more options
enablePasswordDB: true